---
- name: Deploy the VCSA to an ESXi Host
  hosts: localhost
  gather_facts: false

  vars_files:
    - var_vcenter.yml

  tasks:
    - name: Deploy vCenter
      vmware_deploy_ovf:
        hostname: '{{ esxi_address }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        name: '{{ vcenter_hostname }}'
        ovf: '{{ vcsa_ova_file }}'
        wait_for_ip_address: true
        validate_certs: no
        inject_ovf_env: true
        datastore: '{{ datastore }}'
        networks: "{u'Network 1':u'{{vlan_vcenter}}'}"
        properties:
          DeploymentOption.value: '{{ vcsa_size }}'
          guestinfo.cis.appliance.net.addr.family: 'ipv4'
          guestinfo.cis.appliance.net.mode: 'static'
          guestinfo.cis.appliance.net.addr: '{{ vcenter_address }}'
          guestinfo.cis.appliance.net.pnid: "{{ vcenter_hostname }}.{{ domain }}"
          guestinfo.cis.appliance.net.prefix: '{{ net_prefix }}'
          guestinfo.cis.appliance.net.gateway: '{{ net_gateway }}'
          guestinfo.cis.appliance.net.dns.servers: '{{ dns_servers }}'
          guestinfo.cis.appliance.root.passwd: '{{ vcenter_password }}'
          guestinfo.cis.ceip_enabled: "False"
          guestinfo.cis.deployment.autoconfig: 'True'
          guestinfo.cis.vmdir.password: '{{ vcenter_password }}'
          domain: '{{ domain }}'
      delegate_to: localhost
