---
- name: create cluster
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Create Cluster
      community.vmware.vmware_cluster:  
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: "{{ datacenter_name }}"  
        cluster_name: "{{ cluster_name }}"
        state: present  
      delegate_to: localhost
