---
- name: create Datacenter
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Create Datacenter
      community.vmware.vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        validate_certs: no
        state: present
      delegate_to: localhost

