- name: Verifi vcenter
  hosts: localhost
  gather_facts: no
  vars_files:
  - var_vcenter.yml
  - vars.yml
  tasks:
    - name: Verify vCenter is reachable  # kiem tra khi nao vcenter khoi dong xong dich vu thi moi sang buoc tiep theo
      uri:
        url: "https://{{ vcenter_address }}"
        method: GET
        user: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vcenter_status
      retries: 120 # lap lai 120 lan
      delay: 10 # 10s thuc hien get 1 lan 
      until: vcenter_status.status == 200   
