- name: Verifi vcenter
  hosts: localhost
  gather_facts: no
  vars_files:
  - var_vcenter.yml
  - vars.yml
  tasks:
    - name: Verify vCenter is reachable
      uri:
        url: "https://{{ vcenter_address }}"
        method: GET
        user: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vcenter_status
      retries: 120
      delay: 10
      until: vcenter_status.status == 200
